config/routes.rb
Rails.application.routes.draw do

  resources :chatinfos
  get 'about' => 'about#index'
  get "chat_group/:activity_id", to: "chatinfos#chat_group"
  get "chat_onetoone/:to_userid", to: "messages#chat_onetoone"
  root 'users#login'
  get 'home' => 'activities#index'
  resources :admins
  resources :messages
  resources :replies
  resources :relationships
  resources :comments do
    resources :replies
  end
  resources :activities
  resources :participations
  resources :users do
    resources :participations
    resources :activities
    resources :comments
    resources :relationships
  end
  
  controller :messages do
    get 'two_chat/:to_userid'=>:two_chat
    get 'peer_history/:to_userid'=>:peer_history
  end
  controller :chatinfos do
    get 'enter_chat/:activity_id'=>:enter_chat
    get 'group_history/:activity_id'=>:group_history
  end
  controller :users do
    get 'register'=>:new
    post 'register'=>:create
    get 'change_password'=>:change_password
    post 'update_password'=>:update_password
    get 'set_password/:user_id' => 'users#set_password'
    post 'reset_password'=>:reset_password
    get 'login'=>:login
    post 'login'=>:login_confirm
    delete 'logout'=>:logout
  end
  controller :admins do
    get 'adminlogin'=>:adminlogin
    post 'adminlogin'=>:adminlogin_confirm
    delete 'adminlogout'=>:adminlogout
  end
  controller :participations do
    get 'addtoactivity/:activity_id'=>:addtoactivity
    get 'approve_participation/:participation_id/:activity_id'=>:approve_participation
    get 'refuse_participation/:participation_id/:activity_id'=>:refuse_participation
  end
  controller :activities do
  end

end

app/models/participation.rb
class Participation < ActiveRecord::Base
    belongs_to:user
    belongs_to:activity 
    STATUS_TYPES =     ["APPLE_FOR","APPROVED","REFUSED"]
    validates :status,:inclusion=>STATUS_TYPES
end

app/controllers/participations_controller.rb
# encoding: utf-8
class ParticipationsController < ApplicationController
  skip_before_filter :authorize
  before_action :set_participation, only: [:show, :edit, :update, :destroy]

  # GET /participations
  # GET /participations.json
  def index
    if params[:user_id]
      user = User.find_by_id(params[:user_id])
      @participations = user.participations.paginate(:page => params[:page], :per_page => 5).order('
                                                               created_at DESC')
    else
      @participations = Participation.all.paginate(:page => params[:page], :per_page => 5).order('
                                                               created_at DESC')
    end
  end

  # GET /participations/1
  # GET /participations/1.json
  def show
  end

  # GET /participations/new
  def new
    @participation = Participation.new
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations
  # POST /participations.json
  def create
    @participation = Participation.new(participation_params)

    respond_to do |format|
      if @participation.save
        format.html { redirect_to @participation, notice: 'Participation was successfully created.' }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participations/1
  # PATCH/PUT /participations/1.json
  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to @participation, notice: 'Participation was successfully updated.' }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1
  # DELETE /participations/1.json
  def destroy
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to participations_url, notice: 'Participation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
    def addtoactivity
    user = User.find_by_id(session[:user_id])
    participation = user.participations.new
    activity_id = params[:activity_id]
    logger.info "activity_id"+activity_id.to_s
    participation.activity_id = activity_id
    participation.status = 'APPLE_FOR'
    respond_to do |format|
      if participation.save
        format.html { redirect_to participations_path, notice: 'Participation was successfully created.' }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def approve_participation
    update_participation('APPROVED')
  end
  
  def refuse_participation
    update_participation('REFUSED')
  end
  
  def update_participation(type)
    participation_id = params[:participation_id]
    participation = Participation.find_by_id(participation_id)
    activity_id = params[:activity_id]
    activities = Activity.find_by_id(activity_id)
    respond_to do |format|
      if participation.update_attribute(:status, type)
        # format.html { redirect_to @participation, notice: 'Participation was successfully updated.' }
        format.html { redirect_to activities, notice: 'Participation was successfully updated.' }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit }
        # format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participation_params
      params.require(:participation).permit(:status, :activity_id, :user_id)
    end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_for @participation, :html => { :class => "form-horizontal participation" } do |f| %>

  <% if @participation.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@participation.errors.count, "error") %> prohibited this participation from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @participation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :activity_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :activity_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:activity_id) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                participations_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/participations/edit.html.erb
<%- model_class = Participation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/participations/index.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:start_at) %></th>
      <th><%= model_class.human_attribute_name(:end_at) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:part_created_at) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= link_to participation.activity.id, activity_path(participation.activity) %></td>
        <td><%= participation.activity.title %></td>
        <td><%= participation.activity.content %></td>
        <td><%= participation.activity.start_at %></td>
        <td><%= participation.activity.end_at %></td>
        <td><%= participation.activity.location %></td>
        <td><%= participation.activity.category %></td>
        <td><%=l participation.activity.created_at %></td>
        <td><%=l participation.created_at %></td>
        <td><%= participation.activity.user_id %></td>
        <td><%= participation.status %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      activity_path(participation.activity), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<p><%= will_paginate @orders %></p>

app/views/participations/new.html.erb
<%- model_class = Participation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/participations/original_index.html.erb
<%- model_class = Participation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:activity_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= link_to participation.id, participation_path(participation) %></td>
        <td><%= participation.status %></td>
        <td><%= participation.activity_id %></td>
        <td><%= participation.user_id %></td>
        <td><%=l participation.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_participation_path(participation), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      participation_path(participation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_participation_path,
            :class => 'btn btn-primary' %>

app/views/participations/show.html.erb
<%- model_class = Participation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @participation.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:activity_id) %>:</strong></dt>
  <dd><%= @participation.activity_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @participation.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              participations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_participation_path(@participation), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              participation_path(@participation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>