config/routes.rb
Rails.application.routes.draw do

  resources :chatinfos
  get 'about' => 'about#index'
  get "chat_group/:activity_id", to: "chatinfos#chat_group"
  get "chat_onetoone/:to_userid", to: "messages#chat_onetoone"
  root 'users#login'
  get 'home' => 'activities#index'
  resources :admins
  resources :messages
  resources :replies
  resources :relationships
  resources :comments do
    resources :replies
  end
  resources :activities
  resources :participations
  resources :users do
    resources :participations
    resources :activities
    resources :comments
    resources :relationships
  end
  
  controller :messages do
    get 'two_chat/:to_userid'=>:two_chat
    get 'peer_history/:to_userid'=>:peer_history
  end
  controller :chatinfos do
    get 'enter_chat/:activity_id'=>:enter_chat
    get 'group_history/:activity_id'=>:group_history
  end
  controller :users do
    get 'register'=>:new
    post 'register'=>:create
    get 'change_password'=>:change_password
    post 'update_password'=>:update_password
    get 'set_password/:user_id' => 'users#set_password'
    post 'reset_password'=>:reset_password
    get 'login'=>:login
    post 'login'=>:login_confirm
    delete 'logout'=>:logout
  end
  controller :admins do
    get 'adminlogin'=>:adminlogin
    post 'adminlogin'=>:adminlogin_confirm
    delete 'adminlogout'=>:adminlogout
  end
  controller :participations do
    get 'addtoactivity/:activity_id'=>:addtoactivity
    get 'approve_participation/:participation_id/:activity_id'=>:approve_participation
    get 'refuse_participation/:participation_id/:activity_id'=>:refuse_participation
  end
  controller :activities do
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to:user
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]

  # GET /relationships
  # GET /relationships.json
  def index
    if params[:user_id]
      @follows = Relationship.where(from_userid:params[:user_id])
      @followers = Relationship.where(to_userid:params[:user_id])               
    else
      @follows = Relationship.all
      @followers = Relationship.all
    end
  end

  # GET /relationships/1
  # GET /relationships/1.json
  def show
  end

  # GET /relationships/new
  def new
    @relationship = Relationship.new
  end

  # GET /relationships/1/edit
  def edit
  end

  # POST /relationships
  # POST /relationships.json
  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to User.find_by_id(@relationship.to_userid), notice: 'Relationship was successfully created.' }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relationships/1
  # PATCH/PUT /relationships/1.json
  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    @relationship.destroy
    respond_to do |format|
      format.html { redirect_to User.find_by_id(@relationship.to_userid), notice: 'Relationship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relationship
      @relationship = Relationship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relationship_params
      params.require(:relationship).permit(:from_userid, :to_userid)
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_userid %><br>
    <%= f.number_field :from_userid %>
  </div>
  <div class="field">
    <%= f.label :to_userid %><br>
    <%= f.number_field :to_userid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relationships/edit.html.erb
<h1>Editing Relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

app/views/relationships/index.html.erb
<%- model_class = Relationship -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="page-header">
  <h2>Follows:</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @follows.each do |follow| %>
      <% user = User.find_by_id(follow.to_userid)%>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.sex %></td>
        <td>
          <%= link_to t('.more_details', :default => t("helpers.links.more_details")),
                      user_path(follow.to_userid), :class => 'btn btn-default btn-xs' %>
          <%= link_to 'chat',
                      '/two_chat/'+follow.to_userid.to_s, :class => 'btn btn-default btn-xs' %>          

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="page-header">
  <h2>Followers:</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @followers.each do |follower| %>
      <% user = User.find_by_id(follower.from_userid)%>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.sex %></td>
        <td>
          <%= link_to t('.more_details', :default => t("helpers.links.more_details")),
                      user_path(follower.from_userid), :class => 'btn btn-default btn-xs' %>
          <%= link_to 'chat',
                      '/two_chat/'+follower.from_userid.to_s, :class => 'btn btn-default btn-xs' %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/relationships/new.html.erb
<h1>New Relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>

app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From userid:</strong>
  <%= @relationship.from_userid %>
</p>

<p>
  <strong>To userid:</strong>
  <%= @relationship.to_userid %>
</p>

<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %> 