config/routes.rb
Rails.application.routes.draw do

  resources :chatinfos
  get 'about' => 'about#index'
  get "chat_group/:activity_id", to: "chatinfos#chat_group"
  get "chat_onetoone/:to_userid", to: "messages#chat_onetoone"
  root 'users#login'
  get 'home' => 'activities#index'
  resources :admins
  resources :messages
  resources :replies
  resources :relationships
  resources :comments do
    resources :replies
  end
  resources :activities
  resources :participations
  resources :users do
    resources :participations
    resources :activities
    resources :comments
    resources :relationships
  end
  
  controller :messages do
    get 'two_chat/:to_userid'=>:two_chat
    get 'peer_history/:to_userid'=>:peer_history
  end
  controller :chatinfos do
    get 'enter_chat/:activity_id'=>:enter_chat
    get 'group_history/:activity_id'=>:group_history
  end
  controller :users do
    get 'register'=>:new
    post 'register'=>:create
    get 'change_password'=>:change_password
    post 'update_password'=>:update_password
    get 'set_password/:user_id' => 'users#set_password'
    post 'reset_password'=>:reset_password
    get 'login'=>:login
    post 'login'=>:login_confirm
    delete 'logout'=>:logout
  end
  controller :admins do
    get 'adminlogin'=>:adminlogin
    post 'adminlogin'=>:adminlogin_confirm
    delete 'adminlogout'=>:adminlogout
  end
  controller :participations do
    get 'addtoactivity/:activity_id'=>:addtoactivity
    get 'approve_participation/:participation_id/:activity_id'=>:approve_participation
    get 'refuse_participation/:participation_id/:activity_id'=>:refuse_participation
  end
  controller :activities do
  end

end

app/models/user.rb
require 'digest/sha2'
require 'carrierwave/orm/activerecord'

class User < ActiveRecord::Base
    
    mount_uploader :avatar, AvatarUploader
    
    has_many:participations
    has_many:relationships
    has_many:comments
    has_many:join_activities,:through=>:participations
    has_many:activities
    has_many:chatinfos
    
    SEX_TYPES =     ["Male","Female"]
    validates :sex,:inclusion=>SEX_TYPES
    validates :name,:presence=>true,:uniqueness=>true
    validates :password,:presence=>true, :on=> :new
    validates :password,:confirmation => true
    attr_accessor :password_confirmation
    attr_reader :password
    validate :password_must_be_present
    
    def password=(password)
         @password=password
        if password.present?
            generate_salt
            self.hashed_password = self.class.encrypt_password(password,salt)
        end
    end
    
    
    
    def User.encrypt_password(password,salt)
        Digest::SHA2.hexdigest(password+"wibble"+salt)
    end

    def User.authenticate(name,password)
        if user = find_by_name(name)
            if user.hashed_password == encrypt_password(password,user.salt)
                user
            end
        end
    end
    private
        def password_must_be_present
            errors.add(:password,"missing password") unless hashed_password.present?
        end
        
        def generate_salt
            self.salt = self.object_id.to_s + rand.to_s
        end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  skip_before_filter :authorize,:except => :change_password
  #before_filter :authorize_admin, :only => :index
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
    if params[:q]
      @users = User.where("name like ?", "%#{params[:q][:name_cont]}%")
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    render layout: "user"
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.sex = "Male"
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.html { redirect_to home_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        #format.html { render :new }
	      format.html { redirect_to register_url, notice: 'Validation fails.' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        # format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.html { render :show, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def change_password
  end

  def update_password
    respond_to do |format|
      if user = User.authenticate(User.find_by_id(session[:user_id]).name,params[:old_password])
        if params[:password] == params[:password_confirmation]
          user.password = params[:password]
          if user.update_attribute(:password, params[:password])
            session[:user_id] = nil
            format.html { redirect_to login_path, notice: 'User password was successfully updated.' }
            format.json { render :show, status: :ok, location: @user }
          else
            format.html { redirect_to register_path, notice: 'update password failed' }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to change_password_path, notice: 'not the same password' }
        end
      else
        format.html { redirect_to change_password_path, notice: 'invalid old password' }
        # redirect_to 'change_password',:alert=>"invalid old password"
      end
    end
      
  end
  
  def set_password
    user_id = params[:user_id]
    @user = User.find_by_id(user_id)

  end

  def reset_password
    respond_to do |format|
        if params[:password] == params[:password_confirmation]

          user = User.find_by_id(params[:id])
          if user.update_attribute(:password, params[:password])

            format.html { redirect_to users_path, notice: 'User password was successfully updated.' }
            format.json { render :show, status: :ok, location: @user }
          else
            format.html { redirect_to users_path, notice: 'update password failed' }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to users_path, notice: 'not the same password' }
        end

    end
      
  end

  def login
    if session[:user_id]
      redirect_to home_url
    else
      render layout: "user"
    end
  end

  def login_confirm
    if user = User.authenticate(params[:name],params[:password])
      session[:admin_id] = nil
      session[:user_id] = user.id
      redirect_to home_url
    else
      redirect_to login_url,:alert=>"invalid name password"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_url,:alert=>"logged out"
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :hashed_password, :no, :age, :sex, :college, :major, :school_year, :description, :password, :password_confirmation, :old_password, :avatar, :avatar_cache)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_changepass.html.erb
<%= form_tag action="/update_password",  :class => "form-horizontal user" do %>

  <div class="form-group">
    <label class="control-label col-lg-2" for="old_password" >old password:</label>
    <div class="col-lg-10">
      <%= password_field_tag :old_password, params[:old_password], :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-lg-2" for="password" >password:</label>
    <div class="col-lg-10">
      <%= password_field_tag :password,params[:password],  :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-lg-2" for="password_confirmation" >confirm:</label>
    <div class="col-lg-10">
      <%= password_field_tag :password_confirmation,params[:password_confirmation],  :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= submit_tag "change password", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true, :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <div class="form-group">
      <div class="divClass">
        <% if @user.avatar.to_s == "" %>
        <%= image_tag("default.jpg",:id => 'img_preview', :class => "divClass") %>
        <% else %>
        <%= image_tag(@user.avatar_url,:id => 'img_preview', :class => "divClass") %>
        <% end %>
      </div>
    <%= f.file_field :avatar, :id => 'user_avatar'%>
    <%= f.hidden_field :avatar_cache %>
  </div>
  
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  
  <div class="form-group">
    <%= f.label :no, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :no, :class => 'form-control' %>
    </div>
    <%=f.error_span(:no) %>
  </div>
  <div class="form-group">
    <%= f.label :age, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%=f.error_span(:age) %>
  </div>
  <div class="form-group">
    <%= f.label :sex, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :sex,User::SEX_TYPES,{}, class: 'form-control'  %>
    </div>
    <%=f.error_span(:sex) %>
  </div>
  <div class="form-group">
    <%= f.label :college, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :college, :class => 'form-control' %>
    </div>
    <%=f.error_span(:college) %>
  </div>
  <div class="form-group">
    <%= f.label :major, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :major, :class => 'form-control' %>
    </div>
    <%=f.error_span(:major) %>
  </div>
  <div class="form-group">
    <%= f.label :school_year, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :school_year, :class => 'form-control' %>
    </div>
    <%=f.error_span(:school_year) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  
  $("#user_avatar").change(function(){
	  var objUrl = getObjectURL(this.files[0]);
	  console.log("objUrl = "+objUrl);
	  if (objUrl) {
		  $("#img_preview").attr("src", objUrl) ;
	  }
  });
  
  function getObjectURL(file) {
	  var url = null ; 
	if (window.createObjectURL!=undefined) { // basic
		url = window.createObjectURL(file) ;
	} else if (window.URL!=undefined) { // mozilla(firefox)
		url = window.URL.createObjectURL(file) ;
	} else if (window.webkitURL!=undefined) { // webkit or chrome
		url = window.webkitURL.createObjectURL(file) ;
	}
	return url ;
  }
  
</script>

<style type="text/css">

  .divClass{
    width: 150px;
    height: 150px;
  }
        
</style>

app/views/users/_login.html.erb
<%= form_tag action="/login", :class => "form-horizontal user" do%>

  <div class="form-group">
    <label class="control-label col-lg-2" for="name" >Name</label>
    <div class="col-lg-10">
      <%= text_field_tag :name,params[:name], :class => 'form-control' %>
    </div>

  </div>
  <div class="form-group">
    <label for="password" class="control-label col-lg-2">Password</label>
    <div class="col-lg-10">
      <%= password_field_tag :password,params[:name], :class => 'form-control' %>
    </div>

  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
       <div class="already">
            <p>Don't have an account?</p>
            <%= link_to "Sign up",register_path %>
            <%= link_to "An admin",adminlogin_path %>
        </div>
      
    </div>

    <div class="col-lg-offset-2 col-lg-10">
      <%= submit_tag "login", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                activities_path, :class => 'btn btn-default' %>
      
    </div>
  </div>
  
<% end %>

app/views/users/_register.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :confirm, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <div class="already">
            <p>Already have an account?</p>
            <%= link_to "Sign in",login_path %>
            <!--<a href="signin.html">Sign in</a>-->
        </div>
      
    </div>
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                activities_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/_setpass.html.erb
<%= form_tag action="/reset_password",  :class => "form-horizontal user" do %>

  <div class="form-group">
    <label class="control-label col-lg-2" for="id" >id:</label>
    <div class="col-lg-10">
      <%= text_field_tag :id, params[:id], :class => 'form-control',:value =>@user.id %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-lg-2" for="password" >password:</label>
    <div class="col-lg-10">
      <%= password_field_tag :password,params[:password],  :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-lg-2" for="password_confirmation" >confirm:</label>
    <div class="col-lg-10">
      <%= password_field_tag :password_confirmation,params[:password_confirmation],  :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= submit_tag "change password", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/change_password.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Change Password</h1>
</div>
<%= render :partial => 'changepass' %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:no) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%= model_class.human_attribute_name(:college) %></th>
      <th><%= model_class.human_attribute_name(:major) %></th>
      <th><%= model_class.human_attribute_name(:school_year) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.no %></td>
        <td><%= user.age %></td>
        <td><%= user.sex %></td>
        <td><%= user.college %></td>
        <td><%= user.major %></td>
        <td><%= user.school_year %></td>
        <td><%=l user.created_at %></td>
        <td>
          <% if session[:admin_id] %>
            <%= link_to 'reset pass',
                        '/set_password/'+user.id.to_s, :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_user_path(user), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        user_path(user),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% else %>
            <%= link_to t('.more_details', :default => t("helpers.links.more_details")),
                      user_path(user), :class => 'btn btn-default btn-xs' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/login.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Login</h1>
</div>
<%= render :partial => 'login' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Register</h1>
</div>
<%= render :partial => 'register' %>

app/views/users/set_password.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Change Password</h1>
</div>
<%= render :partial => 'setpass' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="divClass">
    <% if @user.avatar.to_s == "" %>
        <%= image_tag("default.jpg", :class => "divClass") %>
    <% else %>
        <%= image_tag(@user.avatar_url, :class => "divClass") %>
    <% end %>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:no) %>:</strong></dt>
  <dd><%= @user.no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @user.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sex) %>:</strong></dt>
  <dd><%= @user.sex %></dd>
  <dt><strong><%= model_class.human_attribute_name(:college) %>:</strong></dt>
  <dd><%= @user.college %></dd>
  <dt><strong><%= model_class.human_attribute_name(:major) %>:</strong></dt>
  <dd><%= @user.major %></dd>
  <dt><strong><%= model_class.human_attribute_name(:school_year) %>:</strong></dt>
  <dd><%= @user.school_year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @user.description %></dd>
</dl>
<% if session[:user_id] == @user.id%>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<% else %>
    <% @relationship=Relationship.where(from_userid:session[:user_id],to_userid:@user.id) %>
    <% if @relationship.size == 0 %>
        <%= form_for :relationship, url: relationships_url  do |f| %>
        
            <div class="form-group">
              <%= f.hidden_field :from_userid, :value => session[:user_id] ,:class => 'form-control'%>
            </div>
        
            <div class="form-group">
              <%= f.hidden_field :to_userid, :value => @user.id ,:class => 'form-control'%>
            </div>
        
            <div class="actions">
              <%= f.submit "follow", :class => 'btn btn-primary'%>
            </div>
            
        <% end %>
    <% else %>
    
        <%= link_to 'unfollow',relationships_url+'/'+@relationship.first.id.to_s,
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
              
    <% end %>
    
<% end %>
<% if session[:admin_id]%>
<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>

<style type="text/css">

  .divClass{
    width: 150px;
    height: 150px;
  }
        
</style>