config/routes.rb
Rails.application.routes.draw do

  resources :chatinfos
  get 'about' => 'about#index'
  get "chat_group/:activity_id", to: "chatinfos#chat_group"
  get "chat_onetoone/:to_userid", to: "messages#chat_onetoone"
  root 'users#login'
  get 'home' => 'activities#index'
  resources :admins
  resources :messages
  resources :replies
  resources :relationships
  resources :comments do
    resources :replies
  end
  resources :activities
  resources :participations
  resources :users do
    resources :participations
    resources :activities
    resources :comments
    resources :relationships
  end
  
  controller :messages do
    get 'two_chat/:to_userid'=>:two_chat
    get 'peer_history/:to_userid'=>:peer_history
  end
  controller :chatinfos do
    get 'enter_chat/:activity_id'=>:enter_chat
    get 'group_history/:activity_id'=>:group_history
  end
  controller :users do
    get 'register'=>:new
    post 'register'=>:create
    get 'change_password'=>:change_password
    post 'update_password'=>:update_password
    get 'set_password/:user_id' => 'users#set_password'
    post 'reset_password'=>:reset_password
    get 'login'=>:login
    post 'login'=>:login_confirm
    delete 'logout'=>:logout
  end
  controller :admins do
    get 'adminlogin'=>:adminlogin
    post 'adminlogin'=>:adminlogin_confirm
    delete 'adminlogout'=>:adminlogout
  end
  controller :participations do
    get 'addtoactivity/:activity_id'=>:addtoactivity
    get 'approve_participation/:participation_id/:activity_id'=>:approve_participation
    get 'refuse_participation/:participation_id/:activity_id'=>:refuse_participation
  end
  controller :activities do
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
    CATEGORY_TYPES = ["Outdoor","Indoor"]
    validates :category,:inclusion=>CATEGORY_TYPES
    has_many:participations,:dependent => :destroy
    has_many:users,:through=>:participations
    has_one:user
    has_many:chatinfos
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # skip_before_filter :authorize,:except => :new
  skip_before_filter :authorize,:except => :new
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    if params[:user_id]
      user = User.find_by_id(params[:user_id])
      @activities = user.activities.paginate(:page => params[:page], :per_page => 5).order('
                                                               created_at DESC')
    else
      @activities = Activity.all.paginate(:page => params[:page], :per_page => 5).order('
                                                               created_at DESC')
    end
    if params[:q]
      @activities = Activity.where("title like ?", "%#{params[:q][:name_cont]}%")
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    
    @comments = Comment.where('activity_id = '+params[:id])
    
  end

  # GET /activities/new
  def new
    if session[:user_id]
      @activity = Activity.new
    else
      redirect_to login_url
    end
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :content, :category, :start_at, :end_at, :location, :user_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity, :html => { :class => "form-horizontal activity" } do |f| %>

  <% if @activity.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @activity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :content, :class => 'form-control' %>
    </div>
    <%=f.error_span(:content) %>
  </div>
  <div class="form-group">
    <%= f.label :category, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :category, :class => 'form-control' %>
    </div>
    <%=f.error_span(:category) %>
  </div>
  <div class="form-group">
    <%= f.label :start_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :start_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:start_at) %>
  </div>
  <div class="form-group">
    <%= f.label :end_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :end_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:end_at) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                activities_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/activities/_new.html.erb
<%= form_for @activity, :html => { :class => "form-horizontal activity" } do |f| %>

  <% if @activity.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @activity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :content, :class => 'form-control' %>
    </div>
    <%=f.error_span(:content) %>
  </div>
  <div class="form-group">
    <%= f.label :start_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.datetime_select :start_at,{}, :class => 'form-control',:style=>'width:18%;display:inline-block;' %>
    </div>
    <%=f.error_span(:start_at) %>
  </div>
  <div class="form-group">
    <%= f.label :end_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.datetime_select :end_at, {},:class => 'form-control',:style=>'width:18%;display:inline-block;' %>
    </div>
    <%=f.error_span(:end_at) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%=f.error_span(:location) %>
  </div>
  <div class="form-group">
    <%= f.label :category, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :category,Activity::CATEGORY_TYPES,{}, class: 'form-control'  %>
    </div>
    <%=f.error_span(:category) %>
  </div>
  <div class="form-group">
    <div class="col-lg-10">
      <%= f.hidden_field :user_id, :class => 'form-control',:value =>session[:user_id] %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                activities_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/activities/edit.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'new' %>

app/views/activities/index.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:start_at) %></th>
      <th><%= model_class.human_attribute_name(:end_at) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:publisher) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= link_to activity.id, activity_path(activity) %></td>
        <td><%= activity.title %></td>
        <td><%= activity.content %></td>
        <td><%= activity.start_at %></td>
        <td><%= activity.end_at %></td>
        <td><%= activity.location %></td>
        <td><%= activity.category %></td>
        <td><%=l activity.created_at %></td>
        <td><%= User.find_by_id(activity.user_id).name %></td>
        <td>
          <% if session[:admin_id] || (session[:user_id] && session[:user_id] == activity.user_id) %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_activity_path(activity), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      activity_path(activity),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% elsif %>
          <%= link_to t('.more_details', :default => t("helpers.links.more_details")),
                      activity_path(activity), :class => 'btn btn-default btn-xs' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/activities/new.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'new' %>

app/views/activities/show.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @activity.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @activity.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_at) %>:</strong></dt>
  <dd><%= @activity.start_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_at) %>:</strong></dt>
  <dd><%= @activity.end_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @activity.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @activity.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:publisher) %>:</strong></dt>
  <dd><%= User.find_by_id(@activity.user_id).name %></dd>
</dl>

<% if session[:user_id] && !(session[:user_id] == @activity.user_id) &&!(@activity.users.index(User.find_by_id(session[:user_id])))%>
<%= link_to "add me to this activity",
              '/addtoactivity/'+@activity.id.to_s, :class => 'btn btn-default'  %>
<% end %>
<%= link_to "enter chat room",
              '/enter_chat/'+@activity.id.to_s, :class => 'btn btn-default'  %>


<%= link_to t('.back', :default => t("helpers.links.back")),
              activities_path, :class => 'btn btn-default'  %>
<% if session[:admin_id] || (session[:user_id] && session[:user_id] == @activity.user_id )%>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_activity_path(@activity), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              activity_path(@activity),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>

<h1>Comments:</h1>

<% @comments.each do |comment| %>
    <h3>
      <strong>From:</strong>
      <%= comment.user.name %>
      <%= comment.content %>
      <%= link_to 'reply', '#', :class => 'btn btn-primary', data: {toggle: "modal", target: "#"+comment.id.to_s } %>
      <div class="modal fade" id="<%= comment.id.to_s %>" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
          <%= form_for :reply, url: replies_url, remote: true do |f| %>
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">添加回复</h4>
              </div>
              <div class="modal-body">
                <div class="form-group">
                    <%= f.text_area :content ,:class => 'form-control'%>
                  </div>
              
                  <div class="form-group">
                    <%= f.hidden_field :user_id, :value => session[:user_id] ,:class => 'form-control'%>
                  </div>
              
                  <div class="form-group">
                    <%= f.hidden_field :comment_id, :value => comment.id ,:class => 'form-control'%>
                </div>
              </div>
              <div class="modal-footer">
                <%= link_to t('.cancel', :default => t("helpers.links.cancel")), '#', :class => 'btn btn-default', data: {dismiss: "modal"} %>
                <%= f.submit :class => 'btn btn-primary', :data => { :"disable-with" => "请稍等..." } %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    
    </h3>
      <% comment.replies.each do |reply|%>
      <h4>
        <strong>From:</strong>
        <%= reply.user.name %>
        <%= reply.content %>
      </h4>
      <% end %>
    
<% end %>

<h1>Add your comment:</h1>
<%= form_for :comment, url: comments_url  do |f| %>

    <div class="form-group">
      <%= f.text_area :content ,:class => 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.hidden_field :user_id, :value => session[:user_id] ,:class => 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.hidden_field :activity_id, :value => @activity.id ,:class => 'form-control'%>
    </div>

    <div class="actions">
      <%= f.submit :class => 'btn btn-primary'%>
    </div>
    
<% end %>

<h1>Joined number:<%=@activity.participations.where(status: 'APPROVED').size %></h1>
<% if (session[:admin_id] || (session[:user_id] && session[:user_id] == @activity.user_id))&& @activity.participations.size > 0%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:no) %></th>
      <th><%= model_class.human_attribute_name(:part_created_at) %></th>
      <th><%= model_class.human_attribute_name(:part_status) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @activity.participations.each do |participation| %>
      <tr>
        <td><%= link_to participation.user.id, user_path(participation.user) %></td>
        <td><%= participation.user.name %></td>
        <td><%= participation.user.no %></td>
        <td><%=l participation.created_at %></td>
        <td><%= participation.status %></td>
        <td>
          <%= link_to 'APPROVE','/approve_participation/'+participation.id.to_s+'/'+@activity.id.to_s, :class => 'btn btn-default btn-xs' %>
          <%= link_to 'REFUSE','/refuse_participation/'+participation.id.to_s+'/'+@activity.id.to_s,:class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
      </tbody>
</table>
    <% elsif @activity.participations.where(status: 'APPROVED').size > 0%>
    <table class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:no) %></th>
      <th><%= model_class.human_attribute_name(:part_created_at) %></th>
      <th><%= model_class.human_attribute_name(:part_status) %></th>
    </tr>
  </thead>
  <tbody>
    <% @activity.participations.where(status: 'APPROVED').each do |participation| %>
      <tr>
        <td><%= link_to participation.user.id, user_path(participation.user) %></td>
        <td><%= participation.user.name %></td>
        <td><%= participation.user.no %></td>
        <td><%=l participation.created_at %></td>
        <td><%= participation.status %></td>
      </tr>
    <% end %>
      </tbody>
</table>
    <% end %>